### ISSUE TITLE
Exception in thread "main" cascading.flow.FlowException: step failed

### ISSUE THREAD

**Issue by vmuraliraju** [jpmml/jpmml-storm#2]
Hi,

we are trying to implement PMML cascading pattern on Hadoop, getting below error

Exception in thread "main" cascading.flow.FlowException: step failed: (1/1) /test/vittabai, with job id: job_1453567420128_0001, please see cluster logs for failure messages
    at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:261)
    at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:162)
    at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
    at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by vruusmann** [comment]
**Please see cluster logs for failure messages**

**Comment by vruusmann** [comment]
Dear HCL Technologies (@hcl.com) people - Please stop spamming the JPMML project.
